/*
 * Customer Orders API
 * API for managing customer orders
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import java.time.LocalDate;
import org.openapitools.client.model.Order;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Disabled
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * Create a new order
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createOrderTest() throws ApiException {
        UUID id = null;
        Order order = null;
        api.createOrder(id, order);
        // TODO: test validations
    }

    /**
     * Delete an order by ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteOrderTest() throws ApiException {
        UUID id = null;
        api.deleteOrder(id);
        // TODO: test validations
    }

    /**
     * Get orders filtered by orderDate and/or status
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getFilteredOrdersTest() throws ApiException {
        LocalDate orderDate = null;
        String status = null;
        List<Order> response = api.getFilteredOrders(orderDate, status);
        // TODO: test validations
    }

    /**
     * Get an order by ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getOrderByIdTest() throws ApiException {
        UUID id = null;
        Order response = api.getOrderById(id);
        // TODO: test validations
    }

    /**
     * Get orders with pagination
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPaginatedOrdersTest() throws ApiException {
        Integer page = null;
        Integer size = null;
        List<Order> response = api.getPaginatedOrders(page, size);
        // TODO: test validations
    }

    /**
     * Update an existing order
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateOrderTest() throws ApiException {
        UUID id = null;
        api.updateOrder(id);
        // TODO: test validations
    }

}
