/**
 * CustomerOrders API
 * API for managing customers and orders.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CustomerOrdersApi);
  }
}(this, function(expect, CustomerOrdersApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CustomerOrdersApi.CustomersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CustomersApi', function() {
    describe('createCustomer', function() {
      it('should call createCustomer successfully', function(done) {
        //uncomment below and update the code to test createCustomer
        //instance.createCustomer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCustomerById', function() {
      it('should call deleteCustomerById successfully', function(done) {
        //uncomment below and update the code to test deleteCustomerById
        //instance.deleteCustomerById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCustomerById', function() {
      it('should call getCustomerById successfully', function(done) {
        //uncomment below and update the code to test getCustomerById
        //instance.getCustomerById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCustomers', function() {
      it('should call getCustomers successfully', function(done) {
        //uncomment below and update the code to test getCustomers
        //instance.getCustomers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateCustomerById', function() {
      it('should call updateCustomerById successfully', function(done) {
        //uncomment below and update the code to test updateCustomerById
        //instance.updateCustomerById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
